name: Build BitBayPay library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore
    - name: Test
      run: dotnet test src --no-build --verbosity normal
    - name: Generate giv version
      uses: codacy/git-version@2.4.0
    - name: Create version file
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: 'packageVersion.txt'
        FILE_DATA: $VERSION
    - name: Bash for GitHub Actions
      uses: juliangruber/read-file-action@v1.0.0
      with:
        path: 'packageVersion.txt' 
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/BitBayPayClient/BitBayPayClient.csproj
        VERSION_FILE_PATH: 'packageVersion.txt'
        VERSION_REGEX: '.*'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
